### PR TITLE
Fixing live crash

### PR DESCRIPTION
**Pull request by Neno0o**

### CODE REVIEW

**Comment by emartynov** [comment]
I would say you should not synchronise such a big chunk of functionality. But at least it should solve the crash.

**Comment by MBing** [comment]
@emartynov agreed, so this is not solving the crash as well?

**Comment by emartynov** [comment]
My God feeling that it should. The comment was about making library code less blocking. But it is up to you. 

The main goal of this MR should be achieved.

**Comment by MBing** [comment]
@emartynov Ok, great! Thanks for the input. Please close the issue if the bug is resolved.

**Pull request merged**
